sudo: false
language: php
matrix:
  fast_finish: true
  include:
  - php: '5.3'
  - php: '5.4'
  - php: '5.5'
  - php: '5.6'
  - php: '7.0'
  - php: '7.1'
before_script:
- export PHPCS_DIR=/tmp/phpcs
- export SNIFFS_DIR=/tmp/sniffs
- git clone -b 2.9 --depth 1 https://github.com/squizlabs/PHP_CodeSniffer.git $PHPCS_DIR
- git clone -b master --depth 1 https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git
  $SNIFFS_DIR
- git clone -b master --depth 1 https://github.com/wimg/PHPCompatibility.git $SNIFFS_DIR/PHPCompatibility
- "$PHPCS_DIR/scripts/phpcs --config-set installed_paths $SNIFFS_DIR"
- phpenv rehash
- npm install -g jscs
- npm install -g jshint
- wget https://develop.svn.wordpress.org/trunk/.jshintrc
- npm install -g grunt-cli
- npm install
- npm install -g grunt-contrib-sass
- npm install -g grunt-checktextdomain
script:
- mkdir -p build/logs
- find -L . -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
- jshint ./assets/js/*.js
- jscs ./assets/js/*.js
- grunt textdomain
- "$PHPCS_DIR/scripts/phpcs -p -s -v -n ./*.php --standard=./phpcs.ruleset.xml --extensions=php"
- "$PHPCS_DIR/scripts/phpcs -p -s -v -n ./**/*.php --standard=./phpcs.ruleset.xml
  --extensions=php --ignore=./woocommerce/*.php,./node_modules/*.php"
- "$PHPCS_DIR/scripts/phpcs -p -s -v -n ./**/**/*.php --standard=./phpcs.ruleset.xml
  --extensions=php --ignore=./woocommerce/**/*.php,./inc/libraries/class-tgm-plugin-activation.php,./node_modules/**/*.php"
- "$PHPCS_DIR/scripts/phpcs -p -s -v -n ./**/**/**/*.php --standard=./phpcs.ruleset.xml
  --extensions=php --ignore=./woocommerce/**/**/*.php,./node_modules/**/**/*.php"
- "$PHPCS_DIR/scripts/phpcs -p -s -v -n ./**/**/**/**/*.php --standard=./phpcs.ruleset.xml
  --extensions=php --ignore=./node_modules/**/**/**/*.php"
- "$PHPCS_DIR/scripts/phpcs -p -s -v -n ./**/**/**/**/**/*.php --standard=./phpcs.ruleset.xml
  --extensions=php --ignore=./node_modules/**/**/**/**/*.php"
notifications:
  email: false
cache:
  directories:
  - node_modules
after_success:
  - grunt build-archive
  - sh set_tags.sh
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: pVuPowd5pVmyRbsQXZpfJsh1UKBRFjfkM+wWMnoYmlQBkKvDqe4YrCSAtJroIo1DlPNgQdVKdlTMTirRpoz1Z4qN0DsBiRfGJxtibZjUi+yQSoraxQxu/QuLllemrHRHbg+oM+oOlORIuVBL946ITMUFACsRV2qZ6D4oHBByDtnF6l5ficdd/0VSHB3WSET5NCxpZ3VYk+t6FYqkEEAJVUpGf+2zN6uRN3/EvjabKrHEKxGGeNbTMMfII8ZIf688lAQ7yBU9aCbjeYXYIR3CNX8lwVsNx4J5/iBmTEQL6O5E9QLBeUO2hiG+bYS2UnCuuKA2g3Q+UJogoS1vQCI35XIjZ7cXdXlE40T1npzr6f3WgvFbKIMAVTlFGw3ggKo2CmBx+2wLf2ERbksRDJ5EFPR+kNKHSZ9HWd9V0KZtsxiwj7S9Zjjphg1h70ZOaBUP2lFc9ZG+T8YCpS6hUDW2CQ8wWmu1RM/b8bY/q60xh9SeCG60cF7thE3dedU9xYYJeuuRkqTT6JJzdQZG2Z9+EdYouDZrSVVkWHs2bFEdv6GtpaPl3F+OAWAjR8/7mSFLZIcfcCHjDTuhxAo0PJNjk+3kMytyY+Bqq0O6xGQ8lUH42SJktFmo5CaIDW/11l83hS4nnFoIijpWuON5dlpf2bL8PS2iaFfq/PeIFGnPQyg=
  file: tyche.zip
  on:
    branch: master
    repo: puikinsh/tyche