sudo: false

language: php

branches:
  except:
- /^v?\d+\.\d+\.\d+$/

matrix:
  fast_finish: true
  include:
  - php: '5.3'
  - php: '5.4'
  - php: '5.6'
  - php: '7.0'
  - php: '7.1'

before_install:
  # Create a git tag of the new version to use
  # If package.json major and minor versions match last tag, then increment last tag. Else use package.json major.minor.0.
  - "{ sed -nE 's/^[ \\t]*\"version\": \"([0-9]{1,}\\.[0-9]{1,}\\.)[0-9x]{1,}\",$/\\1/p' package.json; git describe --abbrev=0 | sed -E 's/^v([0-9]{1,}\\.[0-9]{1,}\\.)([0-9]{1,})$/\\1 \\2/g'; } | tr \"\\n\" \" \" | awk '{printf($1==$2?\"v\"$2$3+1:\"v\"$1\"0\")}' | xargs -I {} git tag -a {} -m \"{}\"\n"
    # Update package.json based on the git tag we just created
  - npm --no-git-tag-version version from-git

before_script:
- export PHPCS_DIR=/tmp/phpcs
- export SNIFFS_DIR=/tmp/sniffs
- git clone -b 2.9 --depth 1 https://github.com/squizlabs/PHP_CodeSniffer.git $PHPCS_DIR
- git clone -b master --depth 1 https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git
  $SNIFFS_DIR
- git clone -b master --depth 1 https://github.com/wimg/PHPCompatibility.git $SNIFFS_DIR/PHPCompatibility
- "$PHPCS_DIR/scripts/phpcs --config-set installed_paths $SNIFFS_DIR"
- phpenv rehash
- npm install -g jscs
- npm install -g jshint
- wget https://develop.svn.wordpress.org/trunk/.jshintrc
- npm install -g grunt-cli
- npm install
- npm install -g grunt-checktextdomain

script:
- mkdir -p build/logs
- find -L . -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
- jshint ./assets/js/*.js
- jscs ./assets/js/*.js
- grunt textdomain
- "$PHPCS_DIR/scripts/phpcs -p -s -v -n ./*.php --standard=./phpcs.ruleset.xml --extensions=php"
- "$PHPCS_DIR/scripts/phpcs -p -s -v -n ./**/*.php --standard=./phpcs.ruleset.xml
  --extensions=php --ignore=./woocommerce/*.php,./inc/class-tgm-plugin-activation.php,./node_modules/*.php"
- "$PHPCS_DIR/scripts/phpcs -p -s -v -n ./**/**/*.php --standard=./phpcs.ruleset.xml
  --extensions=php --ignore=./woocommerce/**/*.php,./node_modules/**/*.php"
- "$PHPCS_DIR/scripts/phpcs -p -s -v -n ./**/**/**/*.php --standard=./phpcs.ruleset.xml
  --extensions=php --ignore=./woocommerce/**/**/*.php,./node_modules/**/**/*.php"
- "$PHPCS_DIR/scripts/phpcs -p -s -v -n ./**/**/**/**/*.php --standard=./phpcs.ruleset.xml
  --extensions=php --ignore=./node_modules/**/**/**/*.php"
- "$PHPCS_DIR/scripts/phpcs -p -s -v -n ./**/**/**/**/**/*.php --standard=./phpcs.ruleset.xml
  --extensions=php --ignore=./node_modules/**/**/**/**/*.php"
- grunt build-archive

notifications:
  email: false

cache:
  directories:
  - node_modules

deploy:
- provider: script
    skip_cleanup: true
    script: git push --tags
    on:
      branch: master
  api_key:
    secure: H+RGXq9P0XU8pvkylJe3eO9NM0pmlNIIKp2/Prx1MVMalZnMTgt3uzdlbsLoPfaSGSJvYr0LlwXrEGC2y2e1hYqNxzmNsbztnfYkZGuri7TkF/2QD4R5+0fpZOnMTjXyt3rkrCISWT6gu9DmRyiPL7ks89L/DoD61xElRFdOGI/mi+RILQqmLCI5mH3PRcSELQ78tHXx3VPteQajRLGD5tXNsktDGtSf40oXT8r8jbwjIdrom4D/ZR3nHG6JfJ4ArA2Rrxc773nl/yEja5TPbz/D8KT4QE/YenRTWqzlxoG2btcjfSCepZfvQbqZTj/PfXvmiGcMVlW0ag0vPWRU7H5hAu8WDAcRKek8Js9cHR+XWmnx6p+DO2uP45h2LkEbV95tjCseyACKWE0xPAqfDYBGmfixDPIclMs/KX7Kba+l6OaGqBKP/bDBynNENBKNEEb1StJzdPgMuKZN++U4NRjn+OKN30CgzJTRHw8liBIlPnnyoHQXUB9OXH2KPqxnJbZsvMAhdgO4o1IGMTg1og8qROPjtMzayueS//UFo671NplJJ6JYe5H+MqHQI2fuaYTFiC/gQ1lGVxpaDM10L40KPoS6iIq+UNF7TolfiNiIDlChCnfKlawJBhX/klU3jEJQ4Z0ZV27tF6tEGDhvnzPvCp3LhLBIMJoVAN/BjtM=
  file: tyche.zip
  on:
    repo: MachoThemes/tyche
    tags: true