sudo: true
language: php
env:
  global:
    - secure: H+RGXq9P0XU8pvkylJe3eO9NM0pmlNIIKp2/Prx1MVMalZnMTgt3uzdlbsLoPfaSGSJvYr0LlwXrEGC2y2e1hYqNxzmNsbztnfYkZGuri7TkF/2QD4R5+0fpZOnMTjXyt3rkrCISWT6gu9DmRyiPL7ks89L/DoD61xElRFdOGI/mi+RILQqmLCI5mH3PRcSELQ78tHXx3VPteQajRLGD5tXNsktDGtSf40oXT8r8jbwjIdrom4D/ZR3nHG6JfJ4ArA2Rrxc773nl/yEja5TPbz/D8KT4QE/YenRTWqzlxoG2btcjfSCepZfvQbqZTj/PfXvmiGcMVlW0ag0vPWRU7H5hAu8WDAcRKek8Js9cHR+XWmnx6p+DO2uP45h2LkEbV95tjCseyACKWE0xPAqfDYBGmfixDPIclMs/KX7Kba+l6OaGqBKP/bDBynNENBKNEEb1StJzdPgMuKZN++U4NRjn+OKN30CgzJTRHw8liBIlPnnyoHQXUB9OXH2KPqxnJbZsvMAhdgO4o1IGMTg1og8qROPjtMzayueS//UFo671NplJJ6JYe5H+MqHQI2fuaYTFiC/gQ1lGVxpaDM10L40KPoS6iIq+UNF7TolfiNiIDlChCnfKlawJBhX/klU3jEJQ4Z0ZV27tF6tEGDhvnzPvCp3LhLBIMJoVAN/BjtM=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: builds@travis-ci.org
    - TRAVIS_REPO_SLUG: MachoThemes/tyche
    - GIT_BRANCH: master
matrix:
  fast_finish: true
  include:
  - php: '5.3'
#  - php: '5.4'
#  - php: '5.6'
#  - php: '7.0'
#  - php: '7.1'
before_script:
- export PHPCS_DIR=/tmp/phpcs
- export SNIFFS_DIR=/tmp/sniffs
- git clone -b 2.9 --depth 1 https://github.com/squizlabs/PHP_CodeSniffer.git $PHPCS_DIR
- git clone -b master --depth 1 https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git
  $SNIFFS_DIR
- git clone -b master --depth 1 https://github.com/wimg/PHPCompatibility.git $SNIFFS_DIR/PHPCompatibility
- "$PHPCS_DIR/scripts/phpcs --config-set installed_paths $SNIFFS_DIR"
- phpenv rehash
- npm install -g jscs
- npm install -g jshint
- wget https://develop.svn.wordpress.org/trunk/.jshintrc
- npm install -g grunt-cli
- npm install
- npm install -g grunt-checktextdomain
script:
- mkdir -p build/logs
- find -L . -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
- jshint ./assets/js/*.js
- jscs ./assets/js/*.js
- grunt textdomain
- "$PHPCS_DIR/scripts/phpcs -p -s -v -n ./*.php --standard=./phpcs.ruleset.xml --extensions=php"
- "$PHPCS_DIR/scripts/phpcs -p -s -v -n ./**/*.php --standard=./phpcs.ruleset.xml
  --extensions=php --ignore=./woocommerce/*.php,./inc/class-tgm-plugin-activation.php,./node_modules/*.php"
- "$PHPCS_DIR/scripts/phpcs -p -s -v -n ./**/**/*.php --standard=./phpcs.ruleset.xml
  --extensions=php --ignore=./woocommerce/**/*.php,./node_modules/**/*.php"
- "$PHPCS_DIR/scripts/phpcs -p -s -v -n ./**/**/**/*.php --standard=./phpcs.ruleset.xml
  --extensions=php --ignore=./woocommerce/**/**/*.php,./node_modules/**/**/*.php"
- "$PHPCS_DIR/scripts/phpcs -p -s -v -n ./**/**/**/**/*.php --standard=./phpcs.ruleset.xml
  --extensions=php --ignore=./node_modules/**/**/**/*.php"
- "$PHPCS_DIR/scripts/phpcs -p -s -v -n ./**/**/**/**/**/*.php --standard=./phpcs.ruleset.xml
  --extensions=php --ignore=./node_modules/**/**/**/**/*.php"
- grunt build-archive
- ./build.sh

notifications:
  email: false
cache:
  directories:
  - node_modules
before_deploy:
  - ./deploy.sh
deploy:
  provider: releases
  api_key:
    secure: ${GH_TOKEN}
  file: ./build/tyche.zip
  skip_cleanup: true
  on:
    repo: MachoThemes/tyche
    tags: false
    all_branches: true
